/**
 * The docs mirror's data layer — every `.md` under `docs/`, read at BUILD TIME.
 *
 * WHY THERE IS NO GENERATOR HERE.
 *
 * The source is plain markdown, so Vite can import it directly. `?raw` yields a file as a
 * string; a **lazy** glob yields one chunk per document, fetched on navigation. Nothing is
 * generated, nothing is committed twice, and the "keep one copy" rule
 * (`docs/00-meta/conventions.md` §4) holds *by construction* rather than by a regeneration
 * step somebody has to remember.
 *
 * An earlier draft of this work proposed a `scripts/_docs_bundle.cjs` generator that
 * converted markdown to HTML at build time. It was dropped: the generator existed only to
 * avoid a runtime markdown library, and since the source is markdown either way the
 * renderer is needed regardless. Dropping it also drops the generated-and-tracked files it
 * would have added to `docs/40-project/artifacts.md` §4, and the `--check` staleness guard
 * they would have needed.
 *
 * WHY THE MANIFEST IS `doc-map.md` AND NOT A NEW FILE.
 *
 * The index needs each document's path, kind and title *without* loading 55 documents.
 * That table already exists, as a document: `docs/00-meta/doc-map.md` is generated by
 * `scripts/_doc_map.cjs` and is **already asserted current** by `tests/docs.mjs`
 * ("doc-map.md is current and complete"). Reading it here means the mirror cannot disagree
 * with the doc-map about a document's kind, and a stale doc-map fails the suite rather than
 * silently mislabelling the sidebar.
 *
 * WHY LAZY, NOT EAGER — and what the public site pays for this.
 *
 * `docs/` is ~440 KB of markdown across 55 files, over half the current JS bundle.
 * `{ eager: true }` (the form `src/admin/ComponentsPage.tsx` uses, which is right for 21
 * small registry files) would put all of it in the entry chunk.
 *
 * Lazy means the opposite: **the entry chunk is unchanged, and the markdown chunks are only
 * requested by a signed-in operator who opens `/admin/docs`.** A visitor to the marketing
 * site downloads none of it. The index costs one small eager file — the ~15 KB doc-map.
 * `tests/docs-mirror.mjs` asserts the glob is lazy, because switching it to eager would be
 * a silent 440 KB regression on the public site.
 *
 * READ-ONLY, AND ALREADY PUBLIC.
 *
 * Every document here is in a public repository and published to the public wiki, so
 * mirroring them adds no exposure. That is a property of the CURRENT content, not a
 * guarantee: a document that must not be public does not belong under `docs/`.
 */

import { renderMarkdown } from "./markdown"

/**
 * One chunk per document, fetched on navigation. Keys are `/docs/…/*.md`.
 *
 * ⚠️ The pattern below cannot be quoted inside a block comment. A glob's `**` followed by
 * its `/` is also the sequence that ends a comment, so a JSDoc line containing the literal
 * pattern closes the comment and the rest of the prose is parsed as code. Measured: `tsc`
 * reported a cascade of syntax errors beginning at line 2 of this file. Describe it in
 * words instead.
 */
const RAW = import.meta.glob("/docs/**/*.md", {
  query: "?raw",
  import: "default",
}) as Record<string, () => Promise<string>>

/** The manifest. One small file, eager — the index cannot work without it. */
const MANIFEST_SOURCE = Object.values(
  import.meta.glob("/docs/00-meta/doc-map.md", {
    query: "?raw",
    import: "default",
    eager: true,
  }) as Record<string, string>,
)[0]

export interface DocEntry {
  /** Repo-relative path, e.g. `docs/60-reference/parity.md`. The routing key. */
  path: string
  /** The glob key, e.g. `/docs/60-reference/parity.md`. */
  key: string
  /** The domain directory, e.g. `60-reference`. `—` for the front door. */
  domain: string
  /** The title, read from the document's own H1 by `_doc_map.cjs`. */
  title: string
  /** The kind the document declares for itself. */
  kind: string
}

/**
 * Parse `doc-map.md`'s table.
 *
 * The row shape is the one `_doc_map.cjs` writes, and the label it carries is the path
 * relative to `docs/` — the same value the generator derived from its own tree walk. If the
 * generator's format changes, this returns nothing and `tests/docs-mirror.mjs` fails on an
 * empty manifest rather than rendering an empty sidebar.
 */
function parseManifest(source: string): DocEntry[] {
  const out: DocEntry[] = []
  let domain = ""
  for (const line of source.split("\n")) {
    const heading = /^###\s+(.+?)\s*$/.exec(line)
    if (heading) {
      domain = heading[1] === "— (the front door)" ? "—" : heading[1]
      continue
    }
    const row = /^\|\s*\[`([^`]+)`\]\(\.\.\/([^)]+)\)\s*\|\s*([a-z]+)\s*\|\s*(.+?)\s*\|$/.exec(line)
    if (!row) continue
    const [, label, , kind, title] = row
    out.push({ path: `docs/${label}`, key: `/docs/${label}`, domain, title, kind })
  }
  return out
}

export const DOC_ENTRIES: readonly DocEntry[] = parseManifest(MANIFEST_SOURCE ?? "")

/** The domains, in the order `doc-map.md` lists them. */
export const DOC_DOMAINS: readonly string[] = [...new Set(DOC_ENTRIES.map((e) => e.domain))]

/** The entry for a repo-relative path, or undefined. */
export function findDoc(path: string): DocEntry | undefined {
  return DOC_ENTRIES.find((e) => e.path === path)
}

function isKnownDoc(path: string): boolean {
  return DOC_ENTRIES.some((e) => e.path === path)
}

/**
 * A document's front matter, read from its own text.
 *
 * The two accepted shapes are the two `tests/docs.mjs` accepts, deliberately: a document
 * whose kind this mirror could not read would be a document whose kind the suite also
 * cannot read, and that is a defect rather than a rendering problem.
 */
export interface FrontMatter {
  kind: string | null
  lastVerified: string | null
}

const KIND_INLINE = /^\*\*Kind:\*\*\s*([A-Za-z]+)/
const KIND_TABLE = /^\|\s*\*\*Kind\*\*\s*\|\s*\*\*([A-Za-z]+)\*\*/
const VERIFIED_INLINE = /^\*\*Last verified:\*\*\s*(.+?)\s*$/
const VERIFIED_TABLE = /^\|\s*\*\*Last verified\*\*\s*\|\s*(.+?)\s*\|/

export function readFrontMatter(source: string): FrontMatter {
  const head = source.split("\n").slice(0, 14)
  let kind: string | null = null
  let lastVerified: string | null = null
  for (const line of head) {
    if (!kind) {
      const m = KIND_INLINE.exec(line) ?? KIND_TABLE.exec(line)
      if (m) kind = m[1].toLowerCase()
    }
    if (!lastVerified) {
      const m = VERIFIED_INLINE.exec(line) ?? VERIFIED_TABLE.exec(line)
      if (m) lastVerified = m[1]
    }
  }
  return { kind, lastVerified }
}

/** A loaded document: the rendered body, and the front matter it was rendered from. */
export interface LoadedDoc {
  html: string
  frontMatter: FrontMatter
}

/**
 * Load and render a document, or null when the path is not a mirrored document.
 *
 * The front matter is read from **the same text the renderer used**, so the badge above the
 * body cannot disagree with the body about the document's kind or its `Last verified` date.
 * Reading it from a second source would be the drift this whole library exists to prevent.
 */
export async function loadDoc(path: string): Promise<LoadedDoc | null> {
  const entry = findDoc(path)
  if (!entry) return null
  const loader = RAW[entry.key]
  if (!loader) return null
  const source = await loader()
  return {
    html: await renderMarkdown(source, entry.path, isKnownDoc),
    frontMatter: readFrontMatter(source),
  }
}

/** Every mirrored path, repo-relative. Read by the suite's source-level parity check. */
export const MIRRORED_PATHS: readonly string[] = Object.keys(RAW).map((k) => k.replace(/^\//, ""))

/** The dashboard URL for a document. */
export function docHref(path: string): string {
  return `/admin/docs?doc=${encodeURIComponent(path)}`
}
