#!/usr/bin/env node
/**
 * Generate `docs/00-meta/doc-map.md` from the docs tree.
 *
 * WHY DERIVED. The document *kind* is declared once, in the document's own front
 * matter. This file is a summary of those declarations — so it cannot disagree with
 * them, and it cannot be the place someone forgets to update.
 *
 * The rule it enforces: every document under `docs/` that is a DOCUMENT (not a domain
 * index, not a template) declares its kind. A document with no kind is the exact defect
 * `00-meta/conventions.md` §2 exists to prevent — it has no date, so it never looks
 * stale, and no assertion, so it never fails.
 *
 * Usage:
 *   node scripts/_doc_map.cjs            # write the file
 *   node scripts/_doc_map.cjs --check    # exit 1 if stale, or if a kind is missing
 */
const fs = require("fs")
const path = require("path")

const ROOT = path.resolve(__dirname, "..")
const DOCS = path.join(ROOT, "docs")
const OUT = path.join(DOCS, "00-meta", "doc-map.md")

/** Two accepted front-matter shapes. */
const KIND_INLINE = /^\*\*Kind:\*\*\s*([A-Za-z]+)/
const KIND_TABLE = /^\|\s*\*\*Kind\*\*\s*\|\s*\*\*([A-Za-z]+)\*\*/

function walk(dir) {
  const out = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, e.name)
    if (e.isDirectory()) out.push(...walk(abs))
    else if (e.name.endsWith(".md")) out.push(abs)
  }
  return out
}

const rel = (abs) => path.relative(ROOT, abs).split(path.sep).join("/")

const files = walk(DOCS).sort()
const rows = []
const missing = []

for (const abs of files) {
  const relPath = rel(abs)
  const src = fs.readFileSync(abs, "utf8")
  const head = src.split("\n").slice(0, 12)

  let kind = null
  const isIndex = path.basename(abs) === "README.md"
  const isTemplate = relPath.includes("/templates/")

  // A template shows an EXAMPLE front matter, so its `**Kind:** dated` line is part of
  // the sample, not a declaration about the template itself. Check the path first —
  // otherwise every template is counted as a dated document.
  if (isTemplate) {
    kind = "template"
  } else {
    for (const line of head) {
      const m = KIND_INLINE.exec(line) || KIND_TABLE.exec(line)
      if (m) {
        kind = m[1].toLowerCase()
        break
      }
    }
  }

  const isSelf = relPath === "docs/README.md"

  if (!kind) {
    if (isIndex) kind = "index"
    else missing.push(relPath)
  }

  const title = (src.match(/^#\s+(.+)$/m) || [, "(untitled)"])[1]
  const domain = relPath === "docs/README.md" ? "— (the front door)" : relPath.split("/")[1]

  rows.push({ relPath, title, domain, kind })
}

if (missing.length) {
  console.error("Documents with no declared kind:")
  for (const m of missing) console.error("  " + m)
  console.error("\nAdd a `**Kind:** derived | dated | living` line to each.")
  console.error("See docs/00-meta/conventions.md §2.")
  process.exit(1)
}

const countBy = (k) => rows.filter((r) => r.kind === k).length
const now = new Date().toISOString().slice(0, 10)

const lines = []
const P = (s = "") => lines.push(s)

P("# Document map")
P()
P("**Kind:** derived · **Generated by:** `node scripts/_doc_map.cjs` · **Never hand-edit.**")
P()
P("Every document under `docs/`, with the kind it declares for itself. Generated by")
P("reading each document's own front matter — so it cannot disagree with them.")
P()
P(`Generated ${now}. **${rows.length} documents.**`)
P()
P("---")
P()
P("## 1. By kind")
P()
P("| Kind | Count | What it means |")
P("|---|---:|---|")
P(`| **derived** | ${countBy("derived")} | Generated from the tree. Never hand-edited; regenerating is the only way to change it. |`)
P(`| **dated** | ${countBy("dated")} | Hand-written, carries \`Last verified:\` with a date and a commit. Goes stale **visibly**. |`)
P(`| **living** | ${countBy("living")} | Hand-written, asserted against the tree by a check. Fails the suite when it drifts. |`)
P(`| **index** | ${countBy("index")} | A domain's front door. Navigation, not content. |`)
P(`| **template** | ${countBy("template")} | A shape to copy. Not a document about this project. |`)
P()
P("A **living** claim written as if it were **dated** is the defect the whole system")
P("exists to prevent — see [`conventions.md` §2](./conventions.md#2-declare-the-documents-kind).")
P()
P("## 2. The map")
P()

let lastDomain = null
for (const r of rows) {
  if (r.domain !== lastDomain) {
    if (lastDomain !== null) P()
    P(`### ${r.domain}`)
    P()
    P("| Document | Kind | Title |")
    P("|---|---|---|")
    lastDomain = r.domain
  }
  P(`| [\`${r.relPath.replace(/^docs\//, "")}\`](../${r.relPath.replace(/^docs\//, "")}) | ${r.kind} | ${r.title} |`)
}

P()
P("---")
P()
P("## 3. Adding a document")
P()
P("1. **Declare its kind** in the front matter. A document with no kind fails")
P("   `node scripts/_doc_map.cjs --check`, and therefore CI.")
P("2. **List it in [`../README.md`](../README.md)** — the human index. `tests/docs.mjs`")
P("   asserts every document appears there exactly once.")
P("3. **Regenerate this file**: `node scripts/_doc_map.cjs`.")
P()

const out = lines.join("\n")

if (process.argv.includes("--check")) {
  const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : ""
  const strip = (s) => s.replace(/^Generated \d{4}-\d{2}-\d{2}\..*$/m, "")
  if (strip(existing) !== strip(out)) {
    console.error("docs/00-meta/doc-map.md is STALE — run: node scripts/_doc_map.cjs")
    process.exit(1)
  }
  console.log("docs/00-meta/doc-map.md is up to date")
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, out, { encoding: "utf8", newline: "\n" })
  console.log(`wrote ${rel(OUT)} (${rows.length} documents)`)
}
